// Production build of the customer app: same code as the demo, switched to the real API with every demo shortcut,
// sample record and prototype label removed (see BUILD in app.js).
//
//   npm run build:app ->  dist/          self-contained web app for the native projects (mobile/, Capacitor webDir)
//                       live/index.html  the production web app at /live on the same Vercel deployment
//
// The demo stays at / for presentations. Options: --api https://api.example.com  sets the server the native app calls.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const arg = k => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : undefined; };
const api = arg('api') || 'https://pgbx-app.vercel.app';
if (!/^https:\/\/[a-z0-9.-]+(:\d+)?$/i.test(api)) { console.error('--api must be an https origin without a path'); process.exit(1); }

function production(html, { assetBase }) {
  let out = html
    .replace('<meta name="pgbx-build" content="demo">', `<meta name="pgbx-build" content="production">\n<meta name="pgbx-api" content="${api}">`)
    .replace(/<meta name="description" content="[^"]*">/, '<meta name="description" content="PGBX: buy Shariah-compliant 999.0 gold and silver at live prices, hold it in your wallet and collect it at PGBX dealers.">')
    .replace(/<div class="page-caption">[^<]*<\/div>\n?/, '')
    .replace('<script type="module" src="app.js"></script>', `<script type="module" src="${assetBase}app.js"></script>`);
  if (!out.includes('content="production"') || !out.includes(`src="${assetBase}app.js"`)) throw new Error('index.html changed: update scripts/build.mjs');
  return out;
}
const index = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// dist/: everything the native app bundles
const dist = path.join(ROOT, 'dist');
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(path.join(dist, 'vendor'), { recursive: true });
fs.writeFileSync(path.join(dist, 'index.html'), production(index, { assetBase: '' }));
for (const f of ['app.js', 'live.js', 'favicon.svg', 'vendor/htm-preact-standalone-3.1.1.module.js', 'vendor/LICENSES.txt']) fs.copyFileSync(path.join(ROOT, f), path.join(dist, f));
fs.copyFileSync(path.join(ROOT, 'mobile', 'bridge.js'), path.join(dist, 'bridge.js'));
// The native app has no server to send security headers, so its policy is in the page: scripts only from the app
// itself (plus Cloudflare's human check when PGBX switches it on), network only to the PGBX API.
const csp = `default-src 'self'; script-src 'self' https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src ${api}; frame-src https://challenges.cloudflare.com; frame-ancestors 'none'; base-uri 'self'; form-action 'none'; object-src 'none'`;
const withBridge = fs.readFileSync(path.join(dist, 'index.html'), 'utf8')
  .replace('<link rel="icon" href="/favicon.svg"', '<link rel="icon" href="favicon.svg"')
  .replace(/<link rel="manifest"[^>]*>\n?/, '')
  .replace('<meta charset="utf-8">', `<meta charset="utf-8">\n<meta http-equiv="Content-Security-Policy" content="${csp}">`)
  .replace('<script type="module" src="app.js"></script>', '<script type="module" src="bridge.js"></script>\n<script type="module" src="app.js"></script>');
fs.writeFileSync(path.join(dist, 'index.html'), withBridge);

// live/: the production web app, sharing the deployed app.js
fs.mkdirSync(path.join(ROOT, 'live'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'live', 'manifest.webmanifest'), JSON.stringify({ ...JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.webmanifest'), 'utf8')), start_url: '/live/', scope: '/live/' }, null, 2) + '\n');
fs.writeFileSync(path.join(ROOT, 'live', 'index.html'), production(index, { assetBase: '/' }).replace('href="/manifest.webmanifest"', 'href="/live/manifest.webmanifest"').replace('<title>PGBX</title>', '<title>PGBX</title>\n<!-- Generated by scripts/build.mjs from index.html. Do not edit. -->'));
console.log(`Built dist/ (native, API ${api}) and live/index.html (web)`);
